---
galaxy_info:
  role_name: logs_archiver
  author: Brandon Mendieta
  description: "Archiva logs renombrando con hostname, IP y fecha."
  company: TuEmpresa
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
dependencies: []